### PR TITLE
Disable right click

### PR DESCRIPTION
**Pull request by Tokikko**
Right click on child image is disabled. This still can not prevent someone from downloading it but it will make things a bit more complex for those who do not know.

### CODE REVIEW

**Review by stacysealky — CHANGES_REQUESTED** [review]
This is great and thanks for your contribution. Could you save the <script> part into a seperate js file and link it? Just trying to keep things decluttered. You can put the separate js file inside '/controllers' :)

**Comment by gnorbsl** [comment]
I'm not sure if putting frontend scripts in controllers is a good idea @stacysealky 

I think since this is a frontend change, the client won't even have access to controllers. Usually controller is reserved for the backend they handle all the logic from the API

I would suggest to put it in the public folder inside /js/ maybe

**Comment by Tokikko** [comment]
Yeah i agree with @gnorbsl . Better to put them inside a js file, controllers are usually meant to be named for the backend. Can i create/put into a js like it was suggested?

**Comment by stacysealky** [comment]
@Tokikko @gnorbsl You are right! There's a ClientJS folder inside public directory. Maybe put it there?

**Comment by Tokikko** [comment]
Ok, i will put it there then.

**Comment by Tokikko** [comment]
Done

**Pull request merged**
