### PR TITLE
Toast modifications

### PR DESCRIPTION
**Pull request by Tokikko**
Moved css nad js files required for toas into footer since they are used everywhere on the site.
Wrapped the call to make toast inside a function since the design is the same for every page, only the message is changing.
Replace alerts with toast messages

### CODE REVIEW

**Comment by stacysealky** [comment]
made small changes to the css file and footer template. 
I think header should have css links instead of footer, just for the loading order.
lmk if this is ok

also add this 
<link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/toastify-js/src/toastify.min.css">
<link rel="stylesheet" type="text/css" href="../css/toast.css">

to the header.ejs template please.

Thanks and great work!

**Comment by Tokikko** [comment]
Did you make those changes already?

**Comment by stacysealky** [comment]
> Did you make those changes already?

yeah, you ok with it?

**Comment by Tokikko** [comment]
Yeah, feel free to merge :)

**Pull request merged**
